---
title: "Untitled"
author: "Elena"
date: "1/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(mclust)
```

```{r}
source(here('growthProfiles.R'))
```

## GMM clustering

```{r}
# deltaOD has mean dOD for each strain/medium pair
dat <- dplyr::select(deltaOD, -strain)
rownames(dat) <- deltaOD$strain

# Apply GMM model, try 1-15 clusters
gp_mc <- Mclust(dat, 1:15)
summary(gp_mc)
```

```{r}
### supplementary figure XX ###
# cluster stats
# note: not all models generate results for all cluster sizes (none if model cannot converge on optimal results)
plot(gp_mc, what = 'BIC', 
     legendArgs = list(x = "bottomright", ncol = 5))

# probabilities of cluster membership
probabilities <- gp_mc$z 
colnames(probabilities) <- paste0('C', 1:7) 

probabilities <- probabilities %>%
  as.data.frame() %>%
  mutate(id = row_number()) %>%
  tidyr::gather(cluster, probability, -id)

ggplot(probabilities, aes(probability)) +
  geom_histogram(bins = 20) +
  facet_wrap(~ cluster, nrow = 2) +
  theme_classic() +
  theme(text = element_text(size = 14))
```

```{r}
# classification of each strain into clusters
strClass <- data.frame(
  strain = deltaOD$strain,
  cluster = gp_mc$classification)

gpMclust <- deltaOD %>% inner_join(strClass, by = 'strain') %>%
  inner_join(dplyr::select(tax, strain, class, order, family), by = 'strain') %>%
  arrange(cluster, class, order, family, strain) %>%
  dplyr::select(-class, -order, -family) 
```

```{r}
### figure 2 heatmap ###
# add phylogeny to the heatmap 
# colors for phylogeny annotations, consistent scheme I've used for a while
phycol <- readxl::read_xlsx(here::here('data', 'newtaxAnnots_colors3 copy.xlsx'), sheet = 'phylum')
ordcol <- readxl::read_xlsx(here::here('data', 'newtaxAnnots_colors3 copy.xlsx'), sheet = 'order')
classcol <- readxl::read_xlsx(here::here('data', 'newtaxAnnots_colors3 copy.xlsx'), sheet = 'class')
famcol <- readxl::read_xlsx(here::here('data', 'newtaxAnnots_colors3 copy.xlsx'), sheet = 'family')
gfccol <- readxl::read_xlsx(here::here('data', 'newtaxAnnots_colors3 copy.xlsx'), sheet = 'gfc')
# for pheatmap, need list of colors with names corresponding to the annotations
colorAnnots <- list(cluster = c('#F8766D', '#CD9600', '#7CAE00', '#00BE67', '#C0C0C0', '#00BFC4', '#00A9FF'),
                    phylum = phycol$color,
                    class = classcol$color,
                    order = ordcol$color,
                    family = famcol$color,
                    gfc = gfccol$color
                    )

# name the list elements
names(colorAnnots$cluster) <- c(1, 2, 3, 4, 5, 6, 7)  
names(colorAnnots$phylum) <- phycol$name
names(colorAnnots$class) <- classcol$name
names(colorAnnots$order) <- ordcol$name
names(colorAnnots$family) <- famcol$name
names(colorAnnots$gfc) <- gfccol$name

# pheatmap style annotations, row names must correspond to samples
t1 <- dplyr::select(gpMclust, strain, cluster) %>% 
  inner_join(dplyr::select(tax, strain, phylum, class, order, family, gnm_GFC), by = 'strain') %>%
  rename(gfc = gnm_GFC)
annotsLCA <- dplyr::select(t1, cluster, class, order, family)
rownames(annotsLCA) <- t1$strain
annotsLCA <- data.frame(annotsLCA)

# df just for heatmap
y <- dplyr::select(gpMclust, -strain, -cluster) %>% ungroup()
rownames(y) <- gpMclust$strain
# heatmap 
pheatmap::pheatmap(t(log10(y+1)),
                   cluster_rows = FALSE,
                   cluster_cols = FALSE,
                   gaps_col = c(14, 28, 36, 45, 49, 53),
                   annotation_legend = FALSE,
                   annotation_col = annotsLCA,
                   annotation_colors = colorAnnots,
                   color = viridis::viridis(100),
                   fontsize_col = 14)

#rm(t1, phycol, ordcol, classcol, famcol, gfccol, annotsLCA, colorAnnots, strClass, y)
```

```{r}
# wrangle cluster data for plots
gpMclust_long <- gpMclust %>%
  pivot_longer(c(-strain, -cluster), names_to = 'medium', values_to = 'dOD') 
gpMclust_long$medium <- factor(gpMclust_long$medium, 
                       levels = c('difcoMB', 'HMBcmpt', 'HMBpep', 'HMBaa', 'HMBlips', 'HMBoligo', 
                                  'HMBorg', 'HMBntrl', 'HMBamisug', 'HMBacdsug', 'HMB--'))
```

```{r}
### figure 2 panels A, B, C ###
a <- gpMclust_long %>%
  ggplot(aes(x = medium, y = dOD)) +
  geom_point(alpha = .5) +
  geom_boxplot(alpha = .7, outlier.size = -1) +
  facet_wrap(~cluster, ncol = 7) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        text = element_text(size = 14)
        ) +
  labs(x = 'Medium',
      y = 'Max Change in OD600')

b <- gpMclust_long %>%
  mutate(growth = ifelse(dOD == 0, 'no', 'yes')) %>%
  ggplot(aes(x = medium, fill = growth)) +
  geom_bar(position = 'fill', color = 'black') +
  facet_wrap(~cluster, ncol = 8) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5), 
        axis.ticks.x = element_blank(), axis.title.x = element_blank(),
        legend.position = "none",
        text = element_text(size = 14),
        strip.background = element_blank(), strip.text = element_blank()) +
  scale_fill_manual(values = c('#000004FF', '#FCFDBFFF')) +
  labs(fill = 'Growth',
       y = "Proportion of Growing Strains",
       x = '')

c <- gpMclust %>%
  inner_join(dplyr::select(tax, strain, phylum, class, order, family, gnm_GFC), by = 'strain') %>%
  rename(gfc = gnm_GFC) %>%
  mutate(dummy = 1) %>%
  ggplot(aes(x = dummy, fill = class)) +
  geom_bar(position = 'fill', color = 'black') +
  facet_grid(~cluster) +
  theme_classic() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom",
        text = element_text(size = 14),
        strip.background = element_blank(), strip.text = element_blank()) +
  guides(fill = "none") +
  scale_fill_viridis_d(aesthetics = 'fill', option = 'plasma', alpha = .8) +
  labs(x = '',
       y = 'Proportion of Class')

cowplot::plot_grid(a,b,c, ncol = 1)
#rm(a, b, c)
```

```{r}
# print the label for classes
gpMclust %>%
  inner_join(dplyr::select(tax, strain, phylum, class, order, family, gnm_GFC), by = 'strain') %>%
  rename(gfc = gnm_GFC) %>%
  mutate(dummy = 1) %>%
  ggplot(aes(x = dummy, fill = class)) +
  geom_bar(position = 'fill', color = 'black') +
  facet_grid(~cluster) +
  theme_classic() +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom",
        text = element_text(size = 14),
        strip.background = element_blank(), strip.text = element_blank()) +
  guides(fill = guide_legend(ncol = 1, title.position = "top")) +
  scale_fill_viridis_d(aesthetics = 'fill', option = 'plasma', alpha = .8) +
  labs(x = '',
       y = 'Proportion of Class')
```

## Test significance of phylogenetic composition of clusters
  
```{r}
# test difference in proportions of strain classes per cluster 
x <- gpMclust %>%
  inner_join(dplyr::select(tax, strain, phylum, class, order, family, gnm_GFC), by = 'strain') %>%
  rename(gfc = gnm_GFC) %>%
  group_by(cluster, class) %>%
  mutate(num = n()) %>%
  dplyr::select(cluster, class, num) %>%
  distinct() %>%
  pivot_wider(names_from = 'class', values_from = 'num') %>%
  ungroup() 
x[is.na(x)] <- 0

y <- dplyr::select(x, -cluster)

# Note that simulate.p.value = TRUE  
set.seed(123)
res.chi <- chisq.test(y, simulate.p.value = TRUE)
res.chi

chisq.test(y)
```

```{r}
### supplemental figure xx ###
# visualize Pearson residuals using the package corrplot
corrplot::corrplot(res.chi$stdres, is.cor = FALSE)

### table S3 ###
z <- (res.chi$stdres)^2
```

## Differences in growth w/i and between clusters

```{r}
### supplemental figure XX ###
# statistically significant difference in cluster growth on each medium
a <- gpMclust_long %>%
  ggplot(aes(x = as.factor(cluster), y = dOD)) +
  geom_point(alpha = .5) +
  geom_boxplot(alpha = .7) +
  facet_wrap(~medium, ncol = 11) +
  #ggpubr::stat_compare_means(label.x = 1.7) +
  theme_classic() +
  theme(text = element_text(size = 14)) +
  labs(title = "Statistically significant differences in growth between clusters",
       y = "Max Change in OD600",
       x= "Cluster")

# Dunn's test for all pairs of clusters on each medium
meds <- colnames(gpMclust)[2:12]
clust.dunn <- tibble()
for (m in meds) {
  dat <- gpMclust %>%
    pivot_longer(difcoMB:`HMB--`, names_to = 'medium', values_to = 'dOD') %>%
    filter(medium == m)
  med.dn <- FSA::dunnTest(dOD ~ as.factor(cluster), dat, method = 'none', two.sided = TRUE)
  x <- med.dn[[2]] %>% separate(Comparison, c("cluster1", "cluster2"), sep = ' - ') %>% 
    mutate(medium = m)
  clust.dunn <- bind_rows(clust.dunn, x)
}

rm(meds, dat, med.dn, x, m)

# correct p.values for multiple comparisons
clust.dunn <- clust.dunn %>%
  dplyr::select(-P.adj) %>%
  mutate(p.adjusted = p.adjust(P.unadj, method = 'BH'),
         sig = ifelse(p.adjusted < 0.05, 'yes', 'no')) %>%
  dplyr::select(medium, cluster1, cluster2, Z, P.unadj, p.adjusted, sig)

# plot
clust.dunn$medium <- factor(clust.dunn$medium, 
                       levels = c('difcoMB', 'HMBcmpt', 'HMBpep', 'HMBaa', 'HMBlips', 'HMBoligo', 
                                  'HMBorg', 'HMBntrl', 'HMBamisug', 'HMBacdsug', 'HMB--'))
b <- clust.dunn %>%
  ggplot(aes(x = cluster1, y = cluster2, color = sig)) +
  geom_point(size = 5) +
  facet_wrap(~medium, ncol = 11) +
  theme_classic() +
  theme(legend.position = "bottom",
        text = element_text(size = 14)) +
  labs(title = 'Pairwise comparisons',
       color = "BH-adjusted p-value < 0.05",
       x = "Cluster 1",
       y = "Cluster 2")

cowplot::plot_grid(a,b, ncol = 1)

#rm(a, b)
```

```{r warning=FALSE}
### supplemental figure XX ###
# statistically significant difference in cluster growth on each medium
a <- gpMclust_long %>%
  ggplot(aes(x = medium, y = dOD)) +
  geom_point(alpha = .5) +
  geom_boxplot(alpha = .7) +
  facet_wrap(~cluster, ncol = 7) +
  #ggpubr::stat_compare_means(label.x = 1.7) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
      text = element_text(size = 14)) +
  labs(title = "Statistically significant differences in growth between media",
       y = "Max Change in OD600",
       x= "Medium")

# Dunn's test for all pairs of clusters on each medium
meds.dunn <- tibble()
for (i in 1:7) {
  dat <- gpMclust %>%
    pivot_longer(difcoMB:`HMB--`, names_to = 'medium', values_to = 'dOD') %>%
    filter(cluster == i)
  med.dn <- FSA::dunnTest(dOD ~ medium, dat, method = 'none', two.sided = TRUE)
  x <- med.dn[[2]] %>% separate(Comparison, c("med1", "med2"), sep = ' - ') %>% 
    mutate(cluster = i)
  meds.dunn <- bind_rows(meds.dunn, x)
}

rm(dat, med.dn, x, i)

# correct p.values for multiple comparisons
meds.dunn <- meds.dunn %>%
  dplyr::select(-P.adj) %>%
  mutate(p.adjusted = p.adjust(P.unadj, method = 'BH'),
         sig = ifelse(p.adjusted < 0.05, 'yes', 'no')) %>%
  dplyr::select(cluster, med1, med2, Z, P.unadj, p.adjusted, sig)

# plot
b <- meds.dunn %>%
  ggplot(aes(x = med1, y = med2, color = sig)) +
  geom_point(size = 5) +
  facet_wrap(~cluster, ncol = 7) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5),
    text = element_text(size = 14),
    legend.position = "bottom") +
  labs(title = 'Pairwise comparisons',
       color = "BH-adjusted p-value < 0.05",
       x = "Medium 1",
       y = "Medium 2")

cowplot::plot_grid(a,b, ncol = 1)

#writexl::write_xlsx(meds.dunn, here('final_figures', 'dunn_test_wiClusters.xlsx'))

#rm(a, b)
```





















