---
title: "Tastiness Index"
author: "Elena"
date: "11/5/2019"
output: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(here)
library(dendextend)
library(pheatmap)
library(viridis)
```

```{r}
# see format_growth_profile.Rmd for explanation of code
source(here('growthProfiles.R'))
```
  
# Calculate max growth rate

```{r}
dfLoop <- cleanGE %>% select(sample, grp2) %>% distinct()

growthRates <- tibble()

for (s in 1:nrow(dfLoop)) {
  dat <- cleanGE %>% filter(sample == dfLoop[[s, 1]] & grp2 == dfLoop[[s, 2]]) 
  x <- diff(dat$OD600)/diff(dat$tmpt)
  y <- tibble(sample = dfLoop[[s, 1]], 
               grp2 = dfLoop[[s, 2]], 
               tmpt = dat$tmpt[-1], 
               slope = x)
  growthRates <- bind_rows(growthRates, y)
}

rm(s, dat, x, y)
```

```{r}
# average replicates, get the max slope and make that the max GR
maxGR <- growthRates %>% 
  group_by(grp2, tmpt) %>% 
  mutate(avgGR = mean(slope), sdGR = sd(slope)) %>% 
  select(grp2, tmpt, avgGR, sdGR) %>% 
  distinct() %>%
  ungroup() %>% 
  group_by(grp2) %>% 
  filter(avgGR == max(avgGR)) %>% 
  rename(maxAvgGR = avgGR, t_maxGR = tmpt) %>%
  separate(grp2, c("exp", "medium", "strain"), sep = "\\.", remove = FALSE) %>%
  ungroup() %>%
  group_by(medium, strain) %>%
  mutate(maxGR = mean(maxAvgGR)) %>%
  select(medium, strain, maxGR) %>%
  distinct()

maxOD <- dODfinal %>%
  ungroup() %>%
  group_by(strain, medium) %>%
  dplyr::select(strain, medium, deltaOD) %>% 
  distinct() 

maxODGR <- maxGR %>%
  inner_join(maxOD, by = c("medium", "strain")) %>%
  mutate(maxGR = ifelse(deltaOD == 0, 0, maxGR))
```

```{r}
maxODGR %>%
  ggplot(aes(x = maxGR, y = deltaOD)) +
  geom_point(alpha = .7) +
  theme_classic() +
  theme(text = element_text(size = 14)) +
  labs(x = "Max Growth Rate (OD600/hour)",
       y = "Max Change in OD600")

res.mod <- lm(deltaOD ~ maxGR, maxODGR)
summary(res.mod)
plot(res.mod)
```
















































